[module]

[module.hugoVersion]
extended = true
min = "0.84.0"

[[module.imports]]
# see https://github.com/olivernn/lunr.js for details
path = "github.com/olivernn/lunr.js"
disable = false
ignoreConfig = false
ignoreImports = false

[[module.imports.mounts]]
source = "lunr.js"
target = "assets/libs/lunr.js"
