################################################################################
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
################################################################################
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"

  - package-ecosystem: "npm"
    directory: "/bootstrap-icons"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"

  - package-ecosystem: "npm"
    directory: "/bootstrap5"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"

  - package-ecosystem: "npm"
    directory: "/dayjs"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"

  - package-ecosystem: "npm"
    directory: "/lazysizes"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"

  - package-ecosystem: "npm"
    directory: "/lunr.js"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"

  - package-ecosystem: "npm"
    directory: "/popper.js"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
