[module]

[module.hugoVersion]
extended = true
min = "0.78.0"

# see https://github.com/iamkun/dayjs for details
[[module.imports]]
path = "github.com/iamkun/dayjs"
disable = false
ignoreConfig = true
ignoreImports = true

[[module.imports.mounts]]
source = "src"
target = "assets/js/dayjs"
